apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enrober
  labels:
    name: enrober
spec:
  replicas: 1
  selector:
    matchLabels:
      component: enrober
  template:
    metadata:
      labels:
        component: enrober
    spec:
      containers:
      - name: enrober
        image: jbowen/enrober:v0.5.0
        env:
          - name: DEPLOY_STATE
            value: "PROD"
          - name: ECR_SECRET
            value: "false"
        ports:
          - containerPort: 9000

