apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enrober
  labels:
    name: enrober
spec:
  replicas: 1
  selector:
    matchLabels:
      name: enrober
  template:
    metadata:
      labels:
        name: enrober
        microservice: "true"
      annotations:
        trafficHosts: "deploy.k8s.local"
        publicPaths: "9000:/beeswax/deploy"
    spec:
      containers:
      - name: enrober
        image: jbowen/enrober:v0
        env:
          - name: DEPLOY_STATE
            value: "PROD"
        ports:
          - containerPort: 9000
      serviceAccount: admin
