apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enrober
  labels:
    name: enrober
spec:
  replicas: 1
  selector:
    matchLabels:
      component: enrober
  template:
    metadata:
      labels:
        component: enrober
        routable: "true"
      annotations:
        projectcalico.org/policy: "allow tcp from cidr 192.168.0.0/16; allow tcp from cidr 10.129.0.0/16"
        publicHosts: "test.k8s.local"
        publicPaths: "9000:/beeswax/deploy"
    spec:
      containers:
      - name: enrober
        image: jbowen/enrober:v0.1.9
        env:
          - name: DEPLOY_STATE
            value: "PROD"
          - name: ECR_SECRET
            value: "false"
        ports:
          - containerPort: 9000

