swagger: '2.0'

info:
  version: "0.0.0"
  title: Enrober

paths:
      
  /environmentGroups/{environmentGroupID}/environments:
    get:
      description: Returns an array of all environments under a specific Environment Group ID 
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      responses:
        200:
          description: Successful response
          schema: 
            type: array
            items:
              $ref: '#/definitions/environment_object'

        403:
          description: Forbidden
        default:
          description: 5xx Errors

    post:
      description: Creates an environment consisting of a kubernetes namespace and a secret. 
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - name: environment_post
        in: body
        description: environment JSON body object
        required: true
        schema:
         properties: 
          environment_name:
            type: string
            description: Name of environment to be created
          hostNames:
            type: array
            description: Array of valid hostnames to accept traffic from
            items: 
              type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/environment_object'
        403:
          description: Forbidden
        default:
          description: 5xx Errors
  
  /environmentGroups/{environmentGroupID}/environments/{environment}:
    get:
      description: Returns an environment consisting of a kubernetes namespace and a secret.
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/environment_object'
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      description: Updates the hostNames array on an environment.
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - name: environment_patch
        in: body
        description: environment JSON body object
        required: false
        schema: 
          properties:
            hostNames:
              description: Array of valid hostnames to accept traffic from
              type: array
              items: 
                type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/environment_object'
        403:
          description: Forbidden
        404: 
          description: Not Found
        default:
          description: 5xx Errors
    
    
    delete:
      description: Deletes an environment consisting of a namespace and a secret.
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
      
  /environmentGroups/{environmentGroupID}/environments/{environment}/deployments:
    get:
      description: Returns a list of all deployments in a given environment.
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
          schema: 
            type: object
            description: Kubernetes DeploymentList object
        403:
          description: Forbidden
        default:
          description: 5xx Errors
    
    post:
      description: Creates a deployment in the given environment.
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
        
      - name: deployment_body
        in: body
        description: JSON Body
        required: true
        schema:
          $ref: '#/definitions/deployment_post'
      responses:
        201:
          description: Created
          schema:
            type: object
            description: Kubernetes Deployment Object
        403:
          description: Forbidden
        default:
          description: 5xx Errors

  /environmentGroups/{environmentGroupID}/environments/{environment}/deployments/{deployment}:
    get:
      description: Returns a deployment matching the given Environment Group ID, Environment Name, and Deployment Name
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            description: Kubernetes Deployment Object
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      description: Updates a deployment matching the given Environment Group ID, Environment Name, and Deployment Name
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      - name: deployment_body
        in: body
        description: JSON Body
        required: true
        schema:
          $ref: '#/definitions/deployment_patch'
      responses:
          200:
            description: Successful response
            schema: 
              type: object
              description: Kubernetes Deployment Object
          403:
            description: Forbidden
          404:
            description: Not Found
          default:
            description: 5xx Errors
    
    delete:
      description: Deletes a deployment matching the given Environment Group ID, Environment Name, and Deployment Name
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
  
#Top level definitions          
definitions:
  deployment_post:
    description: Deployment JSON body object
    properties:
      deploymentName:
        type: string
        description: Name of deployment to be created
      publicHosts: 
        type: string
        description: Where deployment object is routed for public traffic
      privateHosts:
        type: string
        description: Where deployment object is routed for private traffic
      replicas:
        type: integer
        description: How many replicas to be deployed
      ptsURL:
        type: string
        description: URL to pod template spec json
      pts:
        type: object
        description: Pod template spec to create
      envVars:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: string
          
          
        
  deployment_patch:
    description: Deployment JSON body object
    properties:
      publicHosts: 
        type: string
        description: Where deployment object is routed for public traffic
      privateHosts: 
        type: string
        description: Where deployment object is routed for private traffic
      replicas:
        type: integer
        description: How many replicas to be deployed
      ptsURL:
        type: string
        description: URL to pod template spec json
      pts:
        type: object
        description: Kubernetes Pod Template object
  
  environment_object:
    description: Environment JSON object
    properties: 
      name: 
        type: string
        description: Name of environment
      publicSecret:
        type: string
        description: API key for public routing
      privateSecret:
        type: string
        description: API key for private routing
      hostNames:
        type: array
        description: Array of valid hostnames to accept traffic from
        items: 
          type: string
    

#Top Level Path Parameters
parameters:
  environmentGroupIDParam:
    name: environmentGroupID
    in: path
    description: environmentGroupID of environment
    required: true
    type: string
    
  environmentParam:
    name: environment
    in: path
    description: environment to place deployment in
    required: true
    type: string
  
  deploymentParam:
    name: deployment
    in: path
    description: Name of deployment
    required: true
    type: string
        