swagger: '2.0'

info:
  version: "0.0.0"
  title: Enrober

paths:
  /owners:
    get:
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    post:
      parameters:
      - name: owner
        in: body
        description: Owner of namespace
        required: true
        schema:
          type: string
          
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
  /owners/{owner}:
    get:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    delete:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
      
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
      
  /owners/{owner}/namespaces:
    get:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors

    post:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
  

  /owners/{owner}/namespaces/{namespace}:
    get:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    delete:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
      
  /owners/{owner}/namespaces/{namespace}/deployments:
    get:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    post:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      - name: deployment_body
        in: body
        description: JSON Body
        required: true
        schema:
          $ref: '#/definitions/deployment_body'
          
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors

  /owners/{owner}/namespaces/{namespace}/deployments/{deployment}:
    get:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      - name: deployment
        in: path
        description: Name of deployment
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      - name: deployment
        in: path
        description: Name of deployment
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    delete:
      parameters:
      - name: owner
        in: path
        description: Owner of namespace
        required: true
        type: string
        
      - name: namespace
        in: path
        description: Namespace to place deployment in
        required: true
        type: string
        
      - name: deployment
        in: path
        description: Name of deployment
        required: true
        type: string
        
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
          
definitions:
  deployment_body:
    description: Deployment JSON body object
    properties:
      traffic_hosts: 
        type: string
        description: Where deployment object is routed
      traffic_weights:
        type: integer
        description: How much traffic is sent to deployment object
      replicas:
        type: integer
        description: How many replicas to be deployed
      pts_url:
        type: string
        description: URL to pod template spec json
          