swagger: '2.0'

info:
  version: "0.0.0"
  title: Enrober

paths:
  /environmentGroups:
    get:
      description: Returns a list of all Environment Groups
      produces: 
      - application/json
      responses:
        405:
          description: Method not allowed

  /environmentGroups/{environmentGroupID}:
    get:
      description: Returns an Environment Group matching the given Environment Group ID
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      responses:
        405:
          description: Method not allowed
      
  /environmentGroups/{environmentGroupID}/environments:
    get:
      description: Returns a list of all environments under a specific Environment Group ID 
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        default:
          description: 5xx Errors

    post:
      description: Creates an environment and its correpsonding kubernetes namespace matching the given Environment Group ID and Environment Name
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - name: environment_post
        in: body
        description: environment JSON body object
        required: true
        schema:
         properties: 
          environment_name:
            type: string
            description: Name of environment to be created
          publicSecret:
             type: boolean
             description: Set to true if you want a public-api-key secret to be created
          privateSecret:
             type: boolean
             description:  Set to true if you want a private-api-key secret to be created
          hostNames:
            type: array
            items: 
              type: string

      responses:
        201:
          description: Created
        403:
          description: Forbidden
        default:
          description: 5xx Errors
  
  /environmentGroups/{environmentGroupID}/environments/{environment}:
    get:
      description: Returns an environment and its correpsonding kubernetes namespace matching the given Environment Group ID and Environment Name
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      description: Updates an environment, can modify the secret
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - name: environment_patch
        in: body
        description: environment JSON body object
        required: false
        schema: 
          properties:
            publicSecret:
               type: boolean
               description: Set to true if you want a public-api-key secret to be modified or created
            privateSecret:
               type: boolean
               description:  Set to true if you want a private-api-key secret to be modified or recreated
            hostNames:
              type: array
              items: 
                type: string
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404: 
          description: Not Found
        default:
          description: 5xx Errors
    
    
    delete:
      description: Deletes an environment and its correpsonding kubernetes namespace matching the given Environment Group ID and Environment Name
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
      
  /environmentGroups/{environmentGroupID}/environments/{environment}/deployments:
    get:
      description: Returns a list of all deployments in a given environment with the given environment group ID
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        default:
          description: 5xx Errors
    
    post:
      description: Creates a deployment in the given environment with the given environment group ID based on the given deployment_body
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
        
      - name: deployment_body
        in: body
        description: JSON Body
        required: true
        schema:
          $ref: '#/definitions/deployment_body'
      responses:
        201:
          description: Created
        403:
          description: Forbidden
        default:
          description: 5xx Errors

  /environmentGroups/{environmentGroupID}/environments/{environment}/deployments/{deployment}:
    get:
      description: Returns a deployment matching the given Environment Group ID, Environment Name, and Deployment Name
      produces: 
      - application/json
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      description: Updates a deployment matching the given Environment Group ID, Environment Name, and Deployment Name
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      - name: deployment_body
        in: body
        description: JSON Body
        required: true
        schema:
          $ref: '#/definitions/deployment_patch'
      responses:
          200:
            description: Successful response
          403:
            description: Forbidden
          404:
            description: Not Found
          default:
            description: 5xx Errors
    
    delete:
      description: Deletes a deployment matching the given Environment Group ID, Environment Name, and Deployment Name
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
  
#Top level definitions          
definitions:
  deployment_body:
    description: Deployment JSON body object
    properties:
      deploymentName:
        type: string
        description: Name of deployment to be created
      trafficHosts: 
        type: string
        description: Where deployment object is routed
      publicPaths:
        type: string
        description: Path of deployment
      replicas:
        type: integer
        description: How many replicas to be deployed
      ptsURL:
        type: string
        description: URL to pod template spec json
      pts:
        type: object
        description: Pod template spec to create
          
        
  deployment_patch:
    description: Deployment JSON body object
    properties:
      trafficHosts: 
        type: string
        description: Where deployment object is routed
      publicPaths:
        type: string
        description: Path of deployment
      replicas:
        type: integer
        description: How many replicas to be deployed
      ptsURL:
        type: string
        description: URL to pod template spec json
      pts:
        type: object
        description: Pod template spec to create

#Top Level Path Parameters
parameters:
  environmentGroupIDParam:
    name: environmentGroupID
    in: path
    description: environmentGroupID of environment
    required: true
    type: string
    
  environmentParam:
    name: environment
    in: path
    description: environment to place deployment in
    required: true
    type: string
  
  deploymentParam:
    name: deployment
    in: path
    description: Name of deployment
    required: true
    type: string
        