swagger: '2.0'

info:
  version: "0.0.0"
  title: Enrober

paths:
  /environmentGroups:
    get:
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors

    
  /environmentGroups/{environmentGroupID}:
    get:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
          

      
  /environmentGroups/{environmentGroupID}/environments:
    get:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors

    post:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors
  

  /environmentGroups/{environmentGroupID}/environments/{environment}:
    get:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    delete:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
      
  /environmentGroups/{environmentGroupID}/environments/{environment}/deployments:
    get:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    post:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
        
      - name: deployment_body
        in: body
        description: JSON Body
        required: true
        schema:
          $ref: '#/definitions/deployment_body'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        default:
          description: 5xx Errors

  /environmentGroups/{environmentGroupID}/environments/{environment}/deployments/{deployment}:
    get:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    patch:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
    
    delete:
      parameters:
      - $ref: "#/parameters/environmentGroupIDParam"
      - $ref: "#/parameters/environmentParam"
      - $ref: "#/parameters/deploymentParam"
      responses:
        200:
          description: Successful response
        404:
          description: Not Found
        default:
          description: 5xx Errors
  
#Top level definitions          
definitions:
  deployment_body:
    description: Deployment JSON body object
    properties:
      traffic_hosts: 
        type: string
        description: Where deployment object is routed
      traffic_weights:
        type: integer
        description: How much traffic is sent to deployment object
      replicas:
        type: integer
        description: How many replicas to be deployed
      pts_url:
        type: string
        description: URL to pod template spec json

#Top Level Path Parameters
parameters:

  environmentGroupIDParam:
    name: environmentGroupID
    in: path
    description: environmentGroupID of environment
    required: true
    type: string
    
  environmentParam:
    name: environment
    in: path
    description: environment to place deployment in
    required: true
    type: string
  
  deploymentParam:
    name: deployment
    in: path
    description: Name of deployment
    required: true
    type: string
        